/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Stitch "Premium Landing Page (Linear Style)" — exact tokens */
        'on-tertiary-fixed': '#251a00',
        'on-primary': '#00363d',
        'on-tertiary-fixed-variant': '#594400',
        'surface-variant': '#303540',
        'tertiary': '#ffeac0',
        'surface-container-high': '#252a35',
        'surface-container': '#1b1f2a',
        'surface-tint': '#00daf3',
        'error': '#ffb4ab',
        'on-surface': '#dfe2f1',
        'secondary-fixed': '#e5deff',
        'background': '#060a14',
        'on-tertiary': '#3e2e00',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#303540',
        'primary-container': '#00e5ff',
        'on-secondary-fixed': '#1a0063',
        'inverse-primary': '#006875',
        'on-background': '#dfe2f1',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#f3bf26',
        'on-primary-fixed': '#001f24',
        'inverse-on-surface': '#2c303c',
        'secondary-fixed-dim': '#c9bfff',
        'on-tertiary-container': '#6f5500',
        'on-surface-variant': '#bac9cc',
        'secondary': '#c9bfff',
        'surface-container-low': '#171b26',
        'outline': '#849396',
        'surface-dim': '#060a14',
        'on-primary-fixed-variant': '#004f58',
        'on-secondary-fixed-variant': '#4632a4',
        'surface-bright': '#353945',
        'on-primary-container': '#00626e',
        'tertiary-container': '#fec931',
        'secondary-container': '#4834a6',
        'on-secondary': '#2f138e',
        'surface': '#0f131e',
        'surface-container-lowest': '#0a0e18',
        'tertiary-fixed': '#ffdf96',
        'primary-fixed-dim': '#00daf3',
        'on-secondary-container': '#baaeff',
        'primary': '#c3f5ff',
        'error-container': '#93000a',
        'primary-fixed': '#9cf0ff',
        'outline-variant': '#3b494c',
        'inverse-surface': '#dfe2f1',
        /* Brand colors for backward compat */
        brand: {
          navy: '#060a14',
          cyan: '#22d3ee',
          coral: '#ff4c6a',
          amber: '#fbbf24',
          lavender: '#a78bfa',
        },
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
